const fs=require('fs'),vm=require('vm'),assert=require('assert');
const APP=fs.readFileSync('app.js','utf8');
const src=APP.slice(0,APP.indexOf('load();const hash='))+'\nmodule.exports={buildSchedule,calcGames,gameKey,buildTeamSchedule,assignInitialCourts,liveIds,promote,candidatePool,validConfig,maxDisjointPack,selectDisjointGames,rankings,nextCandidates,leagueComplete,playoffState,setupTeamPlayoffs,setupRRPlayoffs,playoffTeamFromCards};';
const sandbox={module:{exports:{}},exports:{},console,Math,Date,Set,Map,Object,Array,Number,String,JSON,window:{},localStorage:{getItem(){return null},setItem(){}},document:{querySelector(){return null},querySelectorAll(){return []}}};vm.createContext(sandbox);vm.runInContext(src,sandbox,{timeout:120000});
const F=sandbox.module.exports;
function make(n,gpp,type,courts=Math.min(3,Math.floor(n/4))){const players=Array.from({length:n},(_,i)=>({id:'P'+String(i+1).padStart(2,'0'),name:'P'+String(i+1).padStart(2,'0'),team:type==='Team vs Team'?(i<n/2?'sky':'net'):null,present:true}));return {id:'TEST',type,playerCount:n,courts,hours:3,gamesPerPlayer:gpp,players,teams:type==='Team vs Team'?{sky:players.filter(p=>p.team==='sky').map(p=>p.id),net:players.filter(p=>p.team==='net').map(p=>p.id)}:null,playerState:Object.fromEntries(players.map(p=>[p.id,{lastPlayed:0,gamesSinceRest:0,partnerCounts:{},opponentCounts:{}}])),playoff:{}};}
function validateSchedule(t){const raw=F.buildSchedule(t);assert(raw&&raw.length===F.calcGames(t.playerCount,t.gamesPerPlayer),`${t.type} ${t.playerCount}/${t.gamesPerPlayer}: wrong count ${raw?.length}`);const count=Object.fromEntries(t.players.map(p=>[p.id,0]));const keys=new Set();for(const g of raw){const ids=[...g.a,...g.b];assert.equal(new Set(ids).size,4,'game must contain 4 distinct players');const k=F.gameKey(...g.a,...g.b);assert(!keys.has(k),'duplicate game');keys.add(k);ids.forEach(id=>count[id]++);if(t.type==='Team vs Team'){assert(g.a.every(id=>t.teams.sky.includes(id)),'Sky side contains Net player');assert(g.b.every(id=>t.teams.net.includes(id)),'Net side contains Sky player');}}for(const p of t.players)assert.equal(count[p.id],t.gamesPerPlayer,`${p.name} games/player mismatch`);return raw;}
const baselineRR=[[4,1],[6,2],[8,2],[10,2],[12,3],[14,2],[16,1],[18,2],[12,9]];
for(const [n,g] of baselineRR){const t=make(n,g,'Round Robin');const raw=validateSchedule(t);console.log('RR',n,g,raw.length,'OK');}
const baselineTVT=[[4,1],[6,2],[8,2],[10,2],[12,9],[14,2],[16,9],[18,8]];
for(const [n,g] of baselineTVT){const t=make(n,g,'Team vs Team');const raw=validateSchedule(t);console.log('TVT',n,g,raw.length,'OK');}
// Initial live courts: every configured court must fill when enough players are checked in.
for(const type of ['Round Robin','Team vs Team'])for(const [n,g] of [[4,1],[6,2],[8,2],[10,2],[12,3],[12,9],[14,2],[16,1],[16,9],[18,2]]){
  const max=Math.min(3,Math.floor(n/4)); if(max<1)continue; const t=make(n,g,type,max); t.games=validateSchedule(t).map((x,i)=>({...x,id:'G'+String(i+1).padStart(2,'0'),status:'queued',court:null,score:null})); const initial=F.assignInitialCourts(t); assert.equal(initial.length,max,`${type} ${n}/${g}: only ${initial.length}/${max} initial courts filled`); const ids=initial.flatMap(x=>[...x.a,...x.b]); assert.equal(new Set(ids).size,4*max,'initial courts overlap players'); assert.equal(new Set(initial.map(x=>x.id)).size,initial.length,'initial duplicate game'); console.log('INITIAL',type,n,g,'courts',max,'OK');
}
// Partial availability: only enough players for one court means only one court starts.
{const t=make(8,2,'Round Robin',2);const raw=validateSchedule(t);t.players.forEach(p=>p.present=false);for(const id of [...raw[0].a,...raw[0].b])t.players.find(p=>p.id===id).present=true;t.games=raw.map((x,i)=>({...x,id:'G'+i,status:'queued',court:null}));const initial=F.assignInitialCourts(t);assert.equal(initial.length,1);console.log('PARTIAL AVAILABILITY OK');}
// Live flow: finishing a court promotes a different eligible game without overlap.
{const t=make(12,3,'Round Robin',2);t.games=validateSchedule(t).map((x,i)=>({...x,id:'G'+i,status:'queued',court:null}));const initial=F.assignInitialCourts(t);assert.equal(initial.length,2);const first=initial[0],second=initial[1];first.status='done';first.court=null;const next=F.promote(t,first.court||1);assert(next&&next.id!==second.id);const live=F.liveIds(t);assert.equal(live.size,8);assert.equal(new Set([...live]).size,8);console.log('LIVE FLOW OK');}
// NEXT / ON-DECK candidate list never reuses a player across candidate games.
{const t=make(12,3,'Round Robin',2);t.games=validateSchedule(t).map((x,i)=>({...x,id:'G'+i,status:'queued',court:null}));const initial=F.assignInitialCourts(t);const flow=F.nextCandidates(t,6);const seen=new Set();for(const g of flow){for(const id of [...g.a,...g.b])assert(!seen.has(id),'NEXT candidate player overlap');for(const id of [...g.a,...g.b])seen.add(id)}assert.equal(new Set(flow.map(g=>g.id)).size,flow.length);console.log('NEXT/ON-DECK UNIQUENESS OK');}
// Rankings: score accounting and sorting.
{const t=make(4,1,'Round Robin',1);t.games=validateSchedule(t).map((x,i)=>({...x,id:'G'+i,status:'done',score:[21,18]}));const r=F.rankings(t);assert.equal(r.length,4);assert(r.every(x=>x.gp===1&&x.w+x.l===1&&x.pf+x.pa===39&&Math.abs(x.pd)===3));console.log('RANKING ACCOUNTING OK');}
// Team-local ranking and playoff pattern for 12–14.
for(const n of [12,14]){const t=make(n,2,'Team vs Team',2);t.games=validateSchedule(t).map((x,i)=>({...x,id:'G'+i,status:'done',score:[21,18]}));const r=F.rankings(t),sky=r.filter(x=>x.team==='sky'),net=r.filter(x=>x.team==='net');assert.equal(sky.length,n/2);assert.equal(net.length,n/2);const p=F.setupTeamPlayoffs(t);assert(p.matches.sf1.sideA===`${sky[0].name} + ${sky[2].name}`);assert(p.matches.sf1.sideB===`${net[1].name} + ${net[3].name}`);assert(p.matches.sf2.sideA===`${sky[1].name} + ${sky[3].name}`);assert(p.matches.sf2.sideB===`${net[0].name} + ${net[2].name}`);console.log('TVT PLAYOFF',n,'OK');}
// Team-local ranking for 16+ qualifier pattern.
{const t=make(16,1,'Team vs Team',3);t.games=validateSchedule(t).map((x,i)=>({...x,id:'G'+i,status:'done',score:[21,18]}));const r=F.rankings(t),sky=r.filter(x=>x.team==='sky'),net=r.filter(x=>x.team==='net');const p=F.setupTeamPlayoffs(t);assert(p.matches.q1.sideA===`${sky[2].name} + ${sky[4].name}`);assert(p.matches.q1.sideB===`${net[3].name} + ${net[5].name}`);assert(p.matches.q2.sideA===`${sky[3].name} + ${sky[5].name}`);assert(p.matches.q2.sideB===`${net[2].name} + ${net[4].name}`);console.log('TVT PLAYOFF 16+ OK');}
// Round Robin playoff setup and trump-card pairing helper.
{const t=make(8,2,'Round Robin',2);t.games=validateSchedule(t).map((x,i)=>({...x,id:'G'+i,status:'done',score:[21,18]}));const r=F.rankings(t);const p=F.setupRRPlayoffs(t);assert.deepEqual(p.matches.sf1,{label:'SEMI-FINAL 1',sideA:'Team 1',sideB:'Team 3'});assert.deepEqual(p.matches.sf2,{label:'SEMI-FINAL 2',sideA:'Team 2',sideB:'Team 4'});p.cards={'1':1,'2':1,'3':2,'4':2,'5':3,'6':3,'7':4,'8':4};assert.deepEqual(F.playoffTeamFromCards(t,1),[r[0].name,r[1].name]);assert.deepEqual(F.playoffTeamFromCards(t,4),[r[6].name,r[7].name]);console.log('RR PLAYOFF + TRUMP CARDS OK');}
assert.equal(F.validConfig(4,1,1,3,'Round Robin'),true);assert.equal(F.validConfig(4,1,1,4,'Round Robin'),false);assert.equal(F.validConfig(4,1,1,1,'Team vs Team'),true);assert.equal(F.validConfig(4,1,1,2,'Team vs Team'),false);assert.equal(F.validConfig(5,1,1,4,'Team vs Team'),false);console.log('CONFIG LIMITS OK');
console.log('ALL COMPREHENSIVE CORE TESTS PASSED');
